### ISSUE TITLE
The build error at the beginning

### ISSUE THREAD

**Issue by livelace** [openshift/jenkins-plugin#61] opened 2016-08-15 05:12 UTC
> Starting "Create OpenShift Resource(s)" with the project "drweb-netcheck".
> ERROR: Build step failed with exception
> java.lang.NullPointerException: trustManager == null
>     at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.java:639)
>     at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftPlugin.httpGet(IOpenShiftPlugin.java:676)
>     at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftApiObjHandler.fetchApiJsonFromApiServer(IOpenShiftApiObjHandler.java:23)
>     at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftApiObjHandler.updateApiTypes(IOpenShiftApiObjHandler.java:66)
>     at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftCreator.coreLogic(IOpenShiftCreator.java:69)
>     at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftPlugin.doItCore(IOpenShiftPlugin.java:310)
>     at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftPlugin.doIt(IOpenShiftPlugin.java:323)
>     at com.openshift.jenkins.plugins.pipeline.OpenShiftBaseStep.perform(OpenShiftBaseStep.java:91)
>     at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
>     at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
>     at hudson.model.Build$BuildExecution.build(Build.java:205)
>     at hudson.model.Build$BuildExecution.doRun(Build.java:162)
>     at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
>     at hudson.model.Run.execute(Run.java:1738)
>     at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
>     at hudson.model.ResourceController.execute(ResourceController.java:98)
>     at hudson.model.Executor.run(Executor.java:410)
> Build step 'Create OpenShift Resource(s)' marked build as failure

1.0.22-SNAPSHOT (private-8a31bd9b-ec2-user)

**Comment by gabemontero** [comment] 2016-08-15 15:58
@livelace - unfortunately, my Create Resource unit test case passes; I am unable to reproduce.

```
Starting "Create OpenShift Resource(s)" with the project "test".
  Created a "ImageStream"
  Created a "BuildConfig"


Exiting "Create OpenShift Resource(s)" successfully, with 2 resource(s) created.
```

Could you reproduce with verbose tracing ?  Are you overriding the token or cert ?

**Comment by livelace** [comment] 2016-08-15 16:03
No, token and cert are the same as they were.

**Comment by livelace** [comment] 2016-08-15 16:09
Complete log https://paste.fedoraproject.org/408841/12773411/

**Comment by gabemontero** [comment] 2016-08-15 16:19
Is Jenkins running inside an OpenShift Pod or external to OpenShift?  I'm not seeing any of the k8s supplied env vars in the env dump.

**Comment by livelace** [comment] 2016-08-15 16:51
@gabemontero No, there is external Jenkins instance. The configuration didn't touched, I just installed openshift pipeline + openshift sync as dependence.

**Comment by livelace** [comment] 2016-08-15 16:57
I have replaced first step token with my admin token - no luck, the same problem.

**Comment by gabemontero** [comment] 2016-08-15 17:04
Yeah the stack trace you posted is related to the cert, not the token.  Since this is an external jenkins, you'll have to supply cert as well as the token.

Try implementing the instructions at https://github.com/openshift/jenkins-plugin#certificates-and-encryption and let's see if I have properly explained what you need to do.

That said, as part of the change to the new openshift-restclient-java/okhttp stuff, I could do a better job of catching this producing a more informative message.  I'll work on changes along those lines.

**Comment by livelace** [comment] 2016-08-15 17:14
Hm, I have read it. I set "SKIP_TLS=True" (string parameter) for this project. But no changes happen. I checked certificates and they are valid (date, dns etc.)

**Comment by gabemontero** [comment] 2016-08-15 17:17
OK, then my latest changes aren't honoring SKIP_TLS as well.  I'll start working on a fix.  Most likely I can have something for you to try in the next hour or so, assuming no interruptions.  Thanks.

**Comment by gabemontero** [comment] 2016-08-15 18:11
ok commit https://github.com/openshift/jenkins-plugin/commit/115cb5752c80322e01896a03c2fc7fc1d6f9db78

and pre-release version https://ci.openshift.redhat.com/jenkins/job/openshift-pipeline-plugin/32/s3/download/openshift-pipeline.hpi

should allow skip tls, including from external jenkins ... i'll wait a bit to see if you have a chance to try it before closing this out.

**Comment by livelace** [comment] 2016-08-15 18:21
@gabemontero  Ok, I see, it's working now. Thanks

FYI https://paste.fedoraproject.org/408905/28525914/

**Comment by gabemontero** [comment] 2016-08-15 18:22
cool deal - thanks for the quick confirm @livelace as well as the logs (helps confirm the behavior) !

**Closed as completed by gabemontero** 2016-08-15 18:22 UTC
