### ISSUE TITLE
Set jenkins+build uri as the reason on build request

### ISSUE THREAD

**Issue by bparees** [openshift/jenkins-plugin#56] opened 2016-07-27 18:49 UTC
now that we can set a cause on a buildrequest, we should set jenkins as the cause with the job uri (same value we are annotating on the build object itself).

https://github.com/openshift/origin/blob/master/pkg/build/api/v1/types.go#L789

@spadgett 

Message should be something like "Jenkins job URI https://blahblah/blah"

the ui will then be able to filter on this value.

**Comment by gabemontero** [comment] 2016-07-27 21:34
This will necessitate a change to openshift-restclient-java (which I can do and then submit a PR for @jcantrill 's review) and invariable upgrade in that dependency.

@bparees @spadgett - I'm assuming we want this prior to 3.3 going out.  Correct?

**Comment by bparees** [comment] 2016-07-27 21:38
@gabemontero ideally.  @spadgett says he can live w/o it.

**Comment by gabemontero** [comment] 2016-08-03 15:08
@bparees @spadgett I have a prototype of this that is working.  Given the amount of additional changes needed to upgrade the openshift-restclient as well as make the modifications to the restclient to set the cause (where I still have to submit a pull for that), I'm not ready to produce a publicly consumable plugin to try, but I can provide a locally built version if you want to try sooner rather than later.

I hope to have the thing ready for public consumption by sometime tomorrow at the latest .... maybe EOB today, but I'm betting that is optimistic.

**Comment by gabemontero** [comment] 2016-08-09 13:22
Quick update - still waiting for the openshift-restclient-java PR to merge.  Not much contention in the PR - just some lag time.

**Comment by jcantrill** [comment] 2016-08-09 14:54
@gabemontero PR merged and 5.0.0-SNAPSHOT deployed

**Comment by gabemontero** [comment] 2016-08-09 15:04
thanks @jcantrill !!

**Comment by gabemontero** [comment] 2016-08-09 17:42
OK @spadgett [here](https://ci.openshift.redhat.com/jenkins/job/openshift-pipeline-plugin/30/s3/download/openshift-pipeline.hpi) is a pre-release version of the plugin that registers a build cause for build triggered from the plugin.

When you get the chance please give it a try, and if we need to make tweaks, let's iterate over them.

I'll leave the issue open for bit in case you get a chance to try in the short term.  Otherwise I'm going to close this out as a result of https://github.com/openshift/jenkins-plugin/commit/070689c63b233529cfa52d60f145d7391e99e50b

**Closed as completed** 2016-08-11 14:18 UTC
